# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20180507_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonim_mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='anonim_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
